services:
  server:
    image: server
    build:
      context: ./
      dockerfile: server.Dockerfile
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8081"]
      retries: 3
      interval: 10s
      start_period: 1s

  client:
    image: client
    build:
      context: ./
      dockerfile: client.Dockerfile
    depends_on:
      server:
        condition: service_healthy